<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>NInfer Manager</AssemblyName>
    <RootNamespace>NInferManager</RootNamespace>
    <ApplicationIcon>Assets\ninfer-manager.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <Version>1.0.0</Version>
    <Product>NInfer Manager</Product>
    <Description>Unofficial lightweight GUI, updater and model manager for NInfer</Description>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <EmbeddedResource Include="Assets\catalog.json" />
    <Content Include="Assets\ninfer-manager.png" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
